database:
  host: localhost
  port: 5432
  username: user
  password: password
  database: postgres

elasticsearch:
  host: localhost
  port: 9200

index:
  reporting:
    name: reporting
    limit: 1000
  ua_user_login_success:
    name: ua_user_login_success
    limit: 1000
  ua_user_login_failure:
    name: ua_user_login_failure
    limit: 1000
