apiVersion: v1
kind: ConfigMap
metadata:
  name: es-reporting
  namespace: mytardis
data:
  settings.yaml: |
    database:
      host: local.postgres
      port: 5432
      username: dummy
      password: dummy
      database: dummy

    elasticsearch:
      host: local.elasticsearch
      port: 9200

    indexes:
      reporting:
        module: reporting
        limit: 1000
      ua_user_login_success:
        module: ua_user_login_success
        limit: 1000
      ua_user_login_failure:
        module: ua_user_login_failure
        limit: 1000
      ua_pageview_dataset:
        module: ua_pageview_dataset
        limit: 1000
      ua_download_datafile:
        module: ua_download_datafile
        limit: 1000
      ua_upload_datafile:
        module: ua_upload_datafile
        limit: 1000
      ua_pushto:
        module: ua_push_to
        limit: 1000
      ua_search:
        module: ua_search
        limit: 1000
      ua_recall:
        module: ua_recall
        limit: 1000

    dumpe:
      path: /mnt/data
      keep: 14
