apiVersion: v1
kind: ConfigMap
metadata:
  name: es-reporting
  namespace: mytardis
data:
  settings.yaml: |
    database:
      host: pgbouncer.postgres
      port: 5432
      username: mytardis
      password: k6cJ2KT7es35GzPj
      database: postgres

    elasticsearch:
      host: elasticsearch7.mytardis
      port: 9200

    index:
      name: datafile
      limit: 10000

    dumpe:
      path: /mnt/data
      keep: 14
