apiVersion: v1
kind: ConfigMap
metadata:
  name: es-reporting
  namespace: mytardis
data:
  settings.yaml: |
    database:
      host: pgbouncer.postgres.svc.cluster.local
      port: 5432
      username: user
      password: pass
      database: postgres

    elasticsearch:
      host: elasticsearch.mytardis.svc.cluster.local
      port: 9200

    index:
      name: reporting
      limit: 10000

    dumpe:
      path: /mnt/data
      keep: 14
